services:
  hbase:
    image: harisekhon/hbase
    container_name: hbase
    ports:
      - "16010:16010"   # HBase Web UI
      - "9090:9090"     # Thrift server
      - "2181:2181"     # Zookeeper
    environment:
      - HBASE_MANAGES_ZK=true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2'

volumes:
  hbase_data: